### ISSUE TITLE
Books Bought at Villagers Don't Function With Anvils

### ISSUE THREAD

**Issue by MysteryTimeTrav** [nulli0n/ExcellentEnchants-old#16]
I'm having an issue on my server where if a book is purchased from a villager with the custom enchantments on it as well as the golden enchant it puts the vanilla enchant only. I don't seem to get any console errors or warnings when it happens. 

Is this intentional?

**Comment by nulli0n** [comment]
If it's Shopkeepers, then it's incompatible.

**Comment by MysteryTimeTrav** [comment]
The issue is from regular villagers. Ones that spawn in the villages and ones that are healed from zombie villagers.

**Comment by nulli0n** [comment]
Make sure that those book enchantments are compatible with the item you want to enchant.
