### ISSUE TITLE
Issue - Tunnel is not giving any experience

### ISSUE THREAD

**Issue by suppatimmo** [nulli0n/ExcellentEnchants-old#19]
Hello,
To reproduce this issue, just simply take any pickaxe with Tunnel enchant, and try to mine anything.
Any ores won't give you EXP, and while mining and sneaking everything is OK.
I've found, that here - [https://github.com/nulli0n/GoldenEnchants/blob/main/GoldenEnchants/src/su/nightexpress/goldenenchants/manager/enchants/tool/EnchantTunnel.java](URL) on line 148 it might be a problem, because normally if this whole method is returned at the beginning, players are getting exp.

**Comment by nulli0n** [comment]
I'll check it soon.

**Comment by suppatimmo** [comment]
Ok ;)

**Comment by nulli0n** [comment]
Will be fixed in the next update.

**Comment by nulli0n** [comment]
Fixed.
