### ISSUE TITLE
1.16.5 Issue - Tunnel Enchant allowing negative durability

### ISSUE THREAD

**Issue by Jurz21** [nulli0n/ExcellentEnchants-old#24]
Hi, it appears the tunnel enchant allows you to go over into negative durability. I am assuming it is not checking for remaining durability and not breaking instead when it hits 0. 

Are you able to fix this? If not our server also has our own guy willing to fix it on our version, but would like your permission.

Thanks, 
![unknown](https://user-images.githubusercontent.com/86375245/123144860-1172a700-d454-11eb-8320-ffa4076573b3.png)

**Comment by nulli0n** [comment]
Fixed.
