### ISSUE TITLE
Description Issue Revisited

### ISSUE THREAD

**Issue by ZackyTeddy** [nulli0n/ExcellentEnchants-old#27]
Hi, hope you are well. I know this issue has been brought up before but is there still no way to break down the enchantment's description into several lines? Reported to have visual issues for players who do not have wider screens. Hope this is considered soon. Thank you for this amazing plugin btw. Super fun in on our server rn. 
![image](https://user-images.githubusercontent.com/58039470/126972629-c3be1298-41f7-49ba-9a67-0bb05d9234f9.png)
![image](https://user-images.githubusercontent.com/58039470/126972697-29c69839-97ff-479a-b433-43d40d72c292.png)

**Comment by nulli0n** [comment]
Done.
